#!/bin/sh -f

./check_app geant4-config 'geant4-config program not found. You have to "source setup" geant4.'

cppflags="`geant4-config --cflags`"
libs="`geant4-config --libs`"

c++ -o media_geo ${cppflags} media_geo.cpp ${libs}
