#!/bin/sh -f

./check_app geant4-config 'geant4-config program not found. You have to "source setup" geant4.'
build_status=$?;if [ ${build_status} != 0 ] ; then exit ${build_status};fi

if [ `uname` = Darwin ] ; then
  export DYLD_LIBRARY_PATH="`geant4-config --prefix`"/lib
else
  libdir="`geant4-config --prefix`/lib"
  if [ -d ${libdir} ] ; then
    export LD_LIBRARY_PATH="${libdir}"
  else
    libdir="`geant4-config --prefix`/lib64"
    if [ -d ${libdir} ] ; then
      export LD_LIBRARY_PATH="${libdir}"
    else
      echo 'Geant4 lib dir not found.'
      exit
    fi
  fi
fi

if [ ! -x ./media_geo ] ; then
  echo 'media_geo not built.'
  exit
fi

./media_geo

